/*
 * Copyright 2017 José A. Pacheco Ondoño - joanpaon@gmail.com.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.japo.java.views;

import java.util.Properties;
import org.japo.java.controllers.Controller;
import org.japo.java.libraries.UtilesApp;
import org.japo.java.models.Model;

/**
 *
 * @author José A. Pacheco Ondoño - joanpaon@gmail.com
 */
public class View extends javax.swing.JFrame {

    // Referencias
    private Model model;
    private Controller control;
    private Properties prpView;

    public View() {
        // Inicializacion Anterior
        initBefore();

        // Creación Vista
        initComponents();

        // Inicializacion Posterior
        initAfter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plantilla Aplicaciones MVC");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    //
    // Inicializacion Anterior
    private void initBefore() {
        // Modelo
        model = new Model();

        // Controlador
        control = new Controller(model, this);

        // Cargar Propiedades Vista
        prpView = UtilesApp.cargarPropiedades("view.properties");

        // Restablecer Estado Vista
        control.restaurarEstadoVista(this, prpView);
    }

    // Inicializacion Posterior
    private void initAfter() {
        // Modelo > Vista
        control.sincronizarModeloVista(model, this);
    }
}
